language: python

python:
- '2.7'
- '3.7'

sudo: required

cache:
- docker

services:
- docker

install:
- sudo pip install --upgrade pip setuptools
- sudo pip install coveralls

before_script:
- docker run -d -p 0.0.0.0:8945:5000 --name hepdata-converter-ws-tests hepdata/hepdata-converter-ws
- sleep 1

script:
- coverage run -m unittest discover hepdata_converter_ws_client/testsuite 'test_*'

after_success:
- ls -al
- coverage --version
- coveralls

deploy:
  skip_existing: true
  provider: pypi
  user: "__token__"
  password:
    secure: "MTlWFxc1U5Y9r6QqXyDge4nui3XyagSyf9POYSHaWFFkzNKGnqwtGNgOZbz6zXGDNgYUo87ZhZ70v8COeKNMJLlQFCNilxfs+gOM8w/eNg2mlaEV8HCep6aFnqnZPJRt8Q6CIi4tsnJeIEvddC0TouNBD5BHGbkbQbz49bZeA7DoVTTxppWCaegRCO7jQhdkxeyDXhG33wm4rcMS7/njhD+6dVAyMCt3cGdc0ZvdokeGteQh9QgbZP19L1RFoY1YdsO3bMIQKNiEtDzP4irYB9oYodYrhqSahcgOV57yfDPVebnpFOwuqZTvIPsyPeUFjo0iOTsy8Z3dqX+lnB0X7Z+wgNyDH2+BC6dJqcw8iHbOb54cFudGfUS5oc/kv3pP9StWwlEh+taqW9ElcmLAgvC+8x1na+o8A1jyozMpHmZqA4RgY+xS6kuUESVxRftQJ9xPAj0+Cu5ponRFHWFVPZjbLDOm6O1tUIgwpNcxl+wmiLDaTcerzXZvm3+LaK2WTkH1rrkVCPfQMQ234inGcQxwNVYaUiGCw5rRBrtOf+D+TgXORxS94AW8q2PdmEqGVK4b+mRnVqiL9kgQbJ5VavAe2+R6z7w9QHYNemCeMr/ovPpIJNYZF2eLFhr2UEuEMt5+8s1evTuG+eK8WmjUGJxql3Ms5fAhfmkfoSDt3qo="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: HEPData/hepdata-converter-ws-client
