language: python
python:
- '2.7'
- '3.7'
sudo: required
cache:
- docker
services:
- docker
install:
- sudo pip install --upgrade pip
- sudo pip install coveralls
- sudo pip install -r requirements.txt

before_script:
- docker run -d -p 0.0.0.0:8945:5000 --name hepdata-converter-ws-tests hepdata/hepdata-converter-ws

script:
- coverage run -m unittest discover hepdata_converter_ws_client/testsuite 'test_*'

after_success:
- ls -al
- coverage --version
- coveralls

after_failure:
- docker logs --details hepdata-converter-ws-tests

deploy:
  provider: pypi
  user: hepdata
  password:
    secure: gByrsSpqtgUKru839J10RUsZCuTw/RwsHHQVRhG5OxdGwS6s/s9zYxKOJJjA1YpiswDNOXVPC4I1pmty971g1kDDIJcV814PTsHUBhf7tDWx6ZJ2mjCoXl7zdPDH4sDxDy6xSzLDwbrS0YN/y7qwGAYAeB7m/cXqndds38q/DrIUfyysDUJZWed3OO9H1lO4AQnB6Kd3mDIxta2N4sBXwuEJIzVTrMIEGj79Gt9lRhMQTXpzduA969OKLGBedKp+blweszkIAGm8VPmvPpiLhgN6siS9tMgX3SufVCnUqXXvRuwPyuKYgq9D8jsBJqpikJxXFB9qTXDLvislj4vTMbMuCxf75o+k4mDLDt6A5tKEo/fUTA7KwhlhvKH769qKKmcUpMX0JYhFlnS4PKZx5PKN9Ia09q5KgRmNfen4ELkwDBWBLpkADCLWRa8Bk2wKU1XFQPdqqC+BbLtcHNwiXY+4IXIonxmKX9hGuFcJ8/wxTRCAC6gkduHFYCBMBA63JfMOI1eSuRsBKd9dgosipmGq7ZJjpwUigDQBz5E2biYrVzMVkIk0B8Si/JPnuaT78t5Wzg/r3EBa+RN5vvYErJH/nd0eb50Jwe51hyk6lnrQx3DqLV/nJMN82cjvCTBivDO2YkcaMY8Gf9Gxm2b8XZk92jtt4Sdm9FkFCct42mI=
  on:
    tags: true
    repo: HEPData/hepdata-converter-ws-client
    branch: master
